dist: xenial
sudo: required

language: go
go: "1.13.x"

jobs:
  include:
    - stage: test
      name: "test all Devfiles with latest released version"
      script:
        - ./scripts/oc-cluster.sh
        - wget https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-amd64
        - chmod +x odo-linux-amd64
        - sudo mv odo-linux-amd64 /usr/local/bin/odo
        - which odo
        - odo login -u developer
        - ./scripts/test.sh
        - odo logout
    - name: "test all Devfiles with latest master"
      script:
        - ./scripts/oc-cluster.sh
        - mkdir -p $GOPATH/src/github.com/
        - git clone --depth=1 https://github.com/openshift/odo  $GOPATH/src/github.com/odo
        - cd $GOPATH/src/github.com/odo; make bin; cd -
        - sudo mv $GOPATH/src/github.com/odo/odo /usr/local/bin/odo
        - odo login -u developer
        - ./scripts/test.sh
        - odo logout
